insert into auth.users(
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    recovery_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
) values (

    '00000000-0000-0000-0000-000000000000',
	'65ef5345-21a6-44d8-989b-d4816ce04dde',
    'authenticated',
    'authenticated',
    'admin@example.com',
    crypt ('password123', gen_salt('bf')),
    current_timestamp,
    current_timestamp,
    current_timestamp,
    '{ "provider":"email","providers":["email"], "claims_admin" : true }',
    jsonb_build_object('first_name', 'John', 'last_name' , 'Smith', 'user_role', 'admin'),
    current_timestamp,
    current_timestamp,
    '',
    '',
    '',
    ''
),
(

    '00000000-0000-0000-0000-000000000000',
	'64ef5345-21a6-44d8-989b-d4816ce04dde',
    'authenticated',
    'authenticated',
    'director@example.com',
    crypt ('password123', gen_salt('bf')),
    current_timestamp,
    current_timestamp,
    current_timestamp,
    '{ "provider":"email","providers":["email"]}',
    jsonb_build_object('first_name', 'Kento', 'last_name' , 'Nanamin', 'user_role', 'director'),
    current_timestamp,
    current_timestamp,
    '',
    '',
    '',
    ''
),(

    '00000000-0000-0000-0000-000000000000',
	'63ef5345-21a6-44d8-989b-d4816ce04dde',
    'authenticated',
    'authenticated',
    'manager@example.com',
    crypt ('password123', gen_salt('bf')),
    current_timestamp,
    current_timestamp,
    current_timestamp,
    '{ "provider":"email","providers":["email"]}',
    jsonb_build_object('first_name', 'Yuta', 'last_name' , 'Okkotsu', 'user_role', 'manager'),
    current_timestamp,
    current_timestamp,
    '',
    '',
    '',
    ''
),(

    '00000000-0000-0000-0000-000000000000',
	'62ef5345-21a6-44d8-989b-d4816ce04dde',
    'authenticated',
    'authenticated',
    'associate@example.com',
    crypt ('password123', gen_salt('bf')),
    current_timestamp,
    current_timestamp,
    current_timestamp,
    '{ "provider":"email","providers":["email"]}',
    jsonb_build_object('first_name', 'Yuji', 'last_name' , 'Itadori', 'user_role', 'associate'),
    current_timestamp,
    current_timestamp,
    '',
    '',
    '',
    ''
);
