name: Test Frontend on Push
run-name: Testing Frontend

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout master
      uses: actions/checkout@main

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Test Build
      run: npm run build


