name: Test-On-Push
run-name: Testing before pushing
on:
  push:
    branches-ignore:
      - 'main'
      - 'dev'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./budgetbuddy-client
          
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Setup .env.local file
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: npm run build
        run: npm run build

