name: Test Backend on Push
run-name: Testing Backend

on:
  push:
    branches:
      - '**'
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name:  Set Up JDK 17 
        uses: actions/setup-java@v3 
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Maven
        uses: mvn --batch-mode --update-snapshots test


